### ISSUE TITLE
When add-on enabled, receive error on Anki startup, locks up, and have to force close Anki

### ISSUE THREAD

**Issue by DoomsDay007** [jac241/anki_killstreaks#25]
I am having an issue with this add-on that when I open Anki, the app is very slow to start up, and when It does I immediately receive an error message. Also, the add-on does not respond when I try to click the entry in the top menu bar. Also, when I try to close Anki, I receive an error message and it will not close so I have to end the process in task manager. I have pasted the error that I received below. Really hoping to get this figured out, because this sounds like a really fun app that will help me enjoy my Anki time a lot more. Thank you for the work that you put into it.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-05 14:56:58

Traceback (most recent call last):
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 316, in _insert_lock_row
    self.execute(
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 372, in execute
    cursor.execute(sql, params)
sqlite3.IntegrityError: UNIQUE constraint failed: yoyo_lock.locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\main.py", line 521, in loadCollection
  File "aqt\main.py", line 661, in moveToState
  File "aqt\main.py", line 668, in _deckBrowserState
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-10>", line 2, in show
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 630, in repl
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\main.py", line 227, in inject_medals_with_js
    achievements=get_achievements_repo().todays_achievements(
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
    self.load_profile()
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 84, in load_profile
    migrate_database(settings=self._db_settings)
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\persistence.py", line 40, in migrate_database
    with backend.lock():
  File "contextlib.py", line 113, in __enter__
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 302, in lock
    self._insert_lock_row(pid, timeout)
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 330, in _insert_lock_row
    raise exceptions.LockTimeout(
579111794._vendor.yoyo.exceptions.LockTimeout: Process 25376 has locked this database (run yoyo break-lock to remove this lock)
Caught exception:
Traceback (most recent call last):
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 316, in _insert_lock_row
    self.execute(
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 372, in execute
    cursor.execute(sql, params)
sqlite3.IntegrityError: UNIQUE constraint failed: yoyo_lock.locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "aqt\main.py", line 142, in on_window_init
  File "aqt\main.py", line 190, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 231, in setupProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 1984, in __call__
  File "anki\hooks.py", line 583, in runHook
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\378638814\main.py", line 257, in onProfileLoaded
    mw.reset(True)
  File "aqt\main.py", line 699, in reset
  File "aqt\main.py", line 661, in moveToState
  File "aqt\main.py", line 668, in _deckBrowserState
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-10>", line 2, in show
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 630, in repl
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\main.py", line 227, in inject_medals_with_js
    achievements=get_achievements_repo().todays_achievements(
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
    self.load_profile()
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 84, in load_profile
    migrate_database(settings=self._db_settings)
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\persistence.py", line 40, in migrate_database
    with backend.lock():
  File "contextlib.py", line 113, in __enter__
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 302, in lock
    self._insert_lock_row(pid, timeout)
  File "C:\Users\Jesus Freak 007\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 330, in _insert_lock_row
    raise exceptions.LockTimeout(
579111794._vendor.yoyo.exceptions.LockTimeout: Process 25376 has locked this database (run yoyo break-lock to remove this lock)

**Comment by andre68723** [comment]
same on Mac with 2.1.35, I think it's somehow related to other installed addons.
