### ISSUE TITLE
can't load addon

### ISSUE THREAD

**Issue by iewuirq** [jac241/anki_killstreaks#4]
i just installed the addon and it won't load, when i restarted anki this error popped up. tried restarting it for a few times but it still won't work.

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Anki Killstreaks':
Traceback (most recent call last):
  File "/Users/dorischan/Library/Application Support/Anki2/addons21/579111794/__init__.py", line 15, in <module>
    os.environ['IN_TEST_SUITE']
  File "os.py", line 669, in __getitem__
KeyError: 'IN_TEST_SUITE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/addons.py", line 71, in loadAddons
  File "/Users/dorischan/Library/Application Support/Anki2/addons21/579111794/__init__.py", line 17, in <module>
    from . import main
  File "/Users/dorischan/Library/Application Support/Anki2/addons21/579111794/main.py", line 29, in <module>
    from .streaks import InitialStreakState, HALO_MULTIKILL_STATES, \
  File "/Users/dorischan/Library/Application Support/Anki2/addons21/579111794/streaks.py", line 11, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

**Comment by jac241** [comment]
I'll push a fix in a couple hours. What version of Anki are you using?

**Comment by iewuirq** [comment]
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.15.2

**Comment by jac241** [comment]
Would you be willing to upgrade Anki to 2.1.15 from 2.1.12? 2.1.15 is the earliest version I tested it on, and it's the earliest version I can support. 2.1.12 isn't available on the Anki archives for me to download to develop a fix for it. Here's where you can download the older versions of Anki: https://apps.ankiweb.net/downloads/archive/
