### ISSUE TITLE
BUG with Anki  {2.1.48}

### ISSUE THREAD

**Issue by aboali1hassona** [jac241/anki_killstreaks#41]
I downloaded this ADDon today And found this Error ↧↧↧ at any time during Reviewing.
 (( Version ⁨2.1.48)) Windows 10
please save it 👀   @jac241 

Error
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-24 16:19:12

Caught exception:
Traceback (most recent call last):
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\188886658\__init__.py", line 21, in <lambda>
cuts[i] = ("2", lambda: self.shortcutFunction(2))
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\188886658\__init__.py", line 10, in shortcutFunction
self._answerCard(response)
File "decorator.py", line 232, in fun
File "anki\hooks.py", line 89, in decorator_wrapper
File "anki\hooks.py", line 83, in repl
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 260, in build_on_answer_wrapper
on_answer(ease=ease, deck_id=deck_id)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 216, in call_method
return getattr(factory_function(), method)(*args, **kwargs)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
self.load_profile()
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 84, in load_profile
migrate_database(settings=self._db_settings)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\persistence.py", line 43, in migrate_database
backend.apply_migrations(backend.to_apply(migrations))
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 435, in apply_migrations
self.apply_migrations_only(migrations, force=force)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 447, in apply_migrations_only
self.apply_one(m, force=force)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 492, in apply_one
migration.process_steps(self, "apply", force=force)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 267, in process_steps
raise exc_info[1].with_traceback(exc_info[2])
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 248, in process_steps
getattr(step, direction)(backend, force)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 310, in apply
getattr(self.step, direction)(backend, force)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 410, in apply
self._execute(cursor, self._apply)
File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 376, in _execute
cursor.execute(stmt)
sqlite3.OperationalError: table achievements already exists

**Comment by aboali1hassona** [comment]
@jac241   TOday I try to reinstall this ADDon. but I faced this Error when opening Anki, closing Anki, and during Review every card.
What happen ??

**Comment by aboali1hassona** [comment]
> I downloaded this ADDon today And found this Error ↧↧↧ at any time during Reviewing. (( Version ⁨2.1.48)) Windows 10 please save it 👀 @jac241
> 
> Error Debug info: Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2021-09-24 16:19:12
> 
> Caught exception: Traceback (most recent call last): File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\188886658__init__.py", line 21, in cuts[i] = ("2", lambda: self.shortcutFunction(2)) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\188886658__init__.py", line 10, in shortcutFunction self._answerCard(response) File "decorator.py", line 232, in fun File "anki\hooks.py", line 89, in decorator_wrapper File "anki\hooks.py", line 83, in repl File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 260, in build_on_answer_wrapper on_answer(ease=ease, deck_id=deck_id) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 216, in call_method return getattr(factory_function(), method)(*args, **kwargs) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method self.load_profile() File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 84, in load_profile migrate_database(settings=self._db_settings) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\persistence.py", line 43, in migrate_database backend.apply_migrations(backend.to_apply(migrations)) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\backends.py", line 435, in apply_migrations self.apply_migrations_only(migrations, force=force) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\backends.py", line 447, in apply_migrations_only self.apply_one(m, force=force) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\backends.py", line 492, in apply_one migration.process_steps(self, "apply", force=force) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\migrations.py", line 267, in process_steps raise exc_info[1].with_traceback(exc_info[2]) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\migrations.py", line 248, in process_steps getattr(step, direction)(backend, force) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\migrations.py", line 310, in apply getattr(self.step, direction)(backend, force) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\migrations.py", line 410, in apply self._execute(cursor, self._apply) File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794_vendor\yoyo\migrations.py", line 376, in _execute cursor.execute(stmt) sqlite3.OperationalError: table achievements already exists
