### ISSUE TITLE
lastest Update 2021-12-14

### ISSUE THREAD

**Issue by aboali1hassona** [jac241/anki_killstreaks#42]
Version ⁨2.1.49 / windows 10 home
i find this error during the past versions ( and this forced me for Togglr this Addon)

I faced this error ↧↧↧ at and page.
![image](https://user-images.githubusercontent.com/91283119/145890133-594384c2-bec1-41d4-8deb-266ed1e8efdb.png)
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-13 22:46:17

Traceback (most recent call last):
  File "aqt\main.py", line 523, in loadCollection
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 679, in _deckBrowserState
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "aqt\deckbrowser.py", line 71, in show
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\main.py", line 227, in inject_medals_with_js
    achievements=get_achievements_repo().todays_achievements(
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
    self.load_profile()
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 84, in load_profile
    migrate_database(settings=self._db_settings)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\persistence.py", line 43, in migrate_database
    backend.apply_migrations(backend.to_apply(migrations))
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 435, in apply_migrations
    self.apply_migrations_only(migrations, force=force)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 447, in apply_migrations_only
    self.apply_one(m, force=force)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\backends.py", line 492, in apply_one
    migration.process_steps(self, "apply", force=force)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 267, in process_steps
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 248, in process_steps
    getattr(step, direction)(backend, force)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 310, in apply
    getattr(self.step, direction)(backend, force)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 410, in apply
    self._execute(cursor, self._apply)
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\579111794\_vendor\yoyo\migrations.py", line 376, in _execute
    cursor.execute(stmt)
sqlite3.OperationalError: table achievements already exists

**Comment by aboali19** [comment]
hi James Castiglione @jac241 
after one month; I hope that you find a solution for this wicked error !!!
THanks
