### ISSUE TITLE
Cant use addon after choosing MWR

### ISSUE THREAD

**Issue by sherlockomes** [jac241/anki_killstreaks#46]
I clicked on Modern Warfare remastered and now I cant get past the error to choose a different game. I really love this add on and ive tried reinstalling and deleting files multiple times. for some reason Anki remembers that I chose MWR even though I tried deleting all the folders associated with the addon. Any help would be greatly appreciated. Thanks

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-19 13:54:32

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\menu.py", line 181, in set_check_for_auto_switch_game
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\game.py", line 16, in load_auto_switch_game_status
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 101, in load_profile
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 129, in _build_reviewing_controller
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\streaks.py", line 1519, in get_next_game_id
ValueError: 'mwr' is not in list

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\menu.py", line 185, in set_check_for_show_chase_mode
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 42, in new_method
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 101, in load_profile
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\controllers.py", line 129, in _build_reviewing_controller
  File "C:\Users\ort7\AppData\Roaming\Anki2\addons21\579111794\streaks.py", line 1519, in get_next_game_id
ValueError: 'mwr' is not in list

**Comment by Amr0100700** [comment]
Version ⁨2.1.66 (70506aeb)⁩

Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨AnkiCraft⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\__init__.py", line 16, in <module>
    from . import main
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\main.py", line 34, in <module>
    from .controllers import (
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\controllers.py", line 13, in <module>
    from . import leaderboards
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\leaderboards.py", line 12, in <module>
    from .persistence import PersistedAchievement, min_datetime
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\persistence.py", line 6, in <module>
    from ._vendor.yoyo import get_backend
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\yoyo\__init__.py", line 27, in <module>
    from .connections import get_backend
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\yoyo\connections.py", line 23, in <module>
    from .migrations import default_migration_table
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\yoyo\migrations.py", line 44, in <module>
    from .utils import plural
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\yoyo\utils.py", line 23, in <module>
    from .config import CONFIG_EDITOR_KEY
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\yoyo\config.py", line 19, in <module>
    from .. import iniherit
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\iniherit\__init__.py", line 9, in <module>
    from .parser import *
  File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\_vendor\iniherit\parser.py", line 14, in <module>
    from six.moves import configparser as CP
ModuleNotFoundError: No module named 'six'
⁩
