### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by oscrey52** [jac241/anki_killstreaks#5]
I am not sure if its just me, but I am having these issues with my loadcollection when I open up the app. I am on the newest version of Anki 2.1.21

Debug info:
Traceback (most recent call last):
  File "aqt/main.py", line 433, in loadCollection
  File "aqt/main.py", line 468, in _loadCollection
  File "aqt/main.py", line 589, in moveToState
  File "aqt/main.py", line 596, in _deckBrowserState
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-104>", line 2, in show
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 522, in repl
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/main.py", line 213, in inject_medals_with_js
    achievements=get_achievements_repo().todays_achievements(
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/controllers.py", line 34, in new_method
    self.load_profile()
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/controllers.py", line 75, in load_profile
    migrate_database(settings=self._db_settings)
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/persistence.py", line 37, in migrate_database
    backend = get_backend(settings.db_uri)
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/connections.py", line 93, in get_backend
    return backend_class(parsed, migration_table)
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/backends.py", line 165, in __init__
    self._connection = self.connect(dburi)
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/backends.py", line 640, in connect
    conn = self.driver.connect(
sqlite3.OperationalError: unable to open database file

And then I get an error saying this,

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-03-09 10:16:25
Add-ons possibly involved: Advanced Browser

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 245, in onOpenProfile
  File "aqt/main.py", line 342, in loadProfile
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-130>", line 2, in loadCollection
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 521, in repl
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-128>", line 2, in loadCollection
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 521, in repl
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-126>", line 2, in loadCollection
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 522, in repl
  File "/Users/reyesos18/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/basic_fields.py", line 75, in myLoadCollection
    mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
AttributeError: 'NoneType' object has no attribute 'db'

**Comment by jac241** [comment]
Hmm. Can you send me a list of your add-ons? You're on macOS right?

**Comment by oscrey52** [comment]
Yes I am!

![image](https://user-images.githubusercontent.com/61986376/76368485-ce47ff80-6306-11ea-8ad6-40709c0a086e.png)
![image](https://user-images.githubusercontent.com/61986376/76368489-d142f000-6306-11ea-844e-2193749cbbf2.png)

**Comment by oscrey52** [comment]
Figured it out, you can't have a hashtag in the name of your profile.
