### ISSUE TITLE
(Anki 23.10) Killstreaks Add on Start up failed

### ISSUE THREAD

**Issue by dreamsofdrd** [jac241/anki_killstreaks#54]
I just installed it and this error popped up. It says Anki hasn't been updates to support the current version. Can anyone help me with this?

I'm on macOS Sonoma.

**Comment by tmujir** [comment]
Also experiencing this issue.

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-07 10:59:31

When loading Anki Killstreaks:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\__init__.py", line 15, in <module>
    from . import main
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\main.py", line 33, in <module>
    from . import chase_mode
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\chase_mode.py", line 14, in <module>
    from . import accounts, tooltips
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\accounts.py", line 6, in <module>
    from .networking import sra_base_url, shared_headers
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\networking.py", line 15, in <module>
    from . import accounts, tooltips
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\tooltips.py", line 10, in <module>
    from .config import local_conf
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\config.py", line 20, in <module>
    from .consts import *
  File "C:\Users\tmuji\AppData\Roaming\Anki2\addons21\anki_killstreaks\consts.py", line 26, in <module>
    addon_path = os.path.dirname(__file__).decode(sys_encoding)
AttributeError: 'str' object has no attribute 'decode'

**Comment by irottah13** [comment]
Similar issue too!

> Error
> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

> When loading '⁨Anki Killstreaks⁩':
> ⁨Traceback (most recent call last):
>   File "aqt.addons", line 246, in loadAddons
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/__init__.py", line 15, in <module>
>     from . import main
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/main.py", line 35, in <module>
>     from .controllers import (
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/controllers.py", line 13, in <module>
>     from . import leaderboards, chase_mode
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/leaderboards.py", line 12, in <module>
>     from .persistence import PersistedAchievement, min_datetime
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/persistence.py", line 6, in <module>
>     from ._vendor.yoyo import get_backend
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/__init__.py", line 27, in <module>
>     from .connections import get_backend
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/connections.py", line 23, in <module>
>     from .migrations import default_migration_table
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/migrations.py", line 44, in <module>
>     from .utils import plural
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/utils.py", line 23, in <module>
>     from .config import CONFIG_EDITOR_KEY
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/yoyo/config.py", line 19, in <module>
>     from .. import iniherit
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/iniherit/__init__.py", line 9, in <module>
>     from .parser import *
>   File "/Users/cjhattori/Library/Application Support/Anki2/addons21/579111794/_vendor/iniherit/parser.py", line 13, in <module>
>     import six
> ModuleNotFoundError: No module named 'six'
> ⁩

**Comment by dyrok** [comment]
Similar Issue

**Comment by avshyz** [comment]
same issue

**Comment by shigeyukey** [comment]
I fixed this add-on for Anki23 + and uploaded it to AnkiWeb.
[🎮Anki Killstreaks - fixed for Anki 23 by Shige](https://ankiweb.net/shared/info/1562475180)

**Comment by avshyz** [comment]
@shigeyukey much appreciated!
